### ISSUE TITLE
Cannot find DB error

### ISSUE THREAD

**Issue by jayshrivastava** [jcavat/docker-lamp#1]
Travelling to localhost:8001 shows this:

Hi! I'm happy

Warning: mysqli_connect(): (HY000/1049): Unknown database 'myDb' in /var/www/html/index.php on line 19

Warning: mysqli_query() expects parameter 1 to be mysqli, boolean given in /var/www/html/index.php on line 23

Fatal error: Uncaught Error: Call to a member function fetch_array() on null in /var/www/html/index.php:27 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 27

**Comment by jcavat** [comment]
Did you have some problems during the build process ? Can you restart from scratch ? Try with `docker-compose build` before

**Comment by jayshrivastava** [comment]
Thanks for getting back to me so quickly! Docker-compose build showed me that it was skipping the deployment of the db. To solve it, I used 
```
docker-compose up db
docker-compose up -d www
docker-compose up -d phpmyadmin
```
Not sure why upping them separately works, but I'll take it. 
More info here: https://stackoverflow.com/questions/38406013/prevent-skip-in-docker-compose

**Comment by jayshrivastava** [comment]
My solution works, but could you explain the steps involved in changing the database (including the credentials)? I tried re building, and I get a permissions error. When I try removing my containers and rebuilding, it does not work either.

**Comment by jcavat** [comment]
if a service is build on an image without Dockerfile it will skip it, it's normal. The command `docker-compose up -d` should suffice but sometimes you need to wait for a while. If you change your credentials I think you have to remove the containers first.
