### ISSUE TITLE
phpMyAdmin fails

### ISSUE THREAD

**Issue by Mebus** [jcavat/docker-lamp#10]
I get the attached error:

![Screenshot_2019-04-20 localhost 8000 db phpMyAdmin 4 8 5](https://user-images.githubusercontent.com/271557/56457315-0f46c680-6379-11e9-84f5-c663082c1b6b.png)

**Comment by jcavat** [comment]
What’s your folder name ? Phpmyadmin with a long volume name seems to cause this problem. Try to rename your folder containing docker-compose with a shorter name.

**Comment by jcavat** [comment]
Feedback please !?

**Comment by Mebus** [comment]
Using mysql5.7 fixed the issue for me.

**Comment by jcavat** [comment]
Changing the folder name for v8 should fix the problem.
