### ISSUE TITLE
Error While connecting to Database

### ISSUE THREAD

**Issue by muhammadnaveel** [jcavat/docker-lamp#17]
Hi, I am getting an error:

Warning: mysqli_connect(): (HY000/1130): Host 'dockerapp_www_1.dockerapp_default' is not allowed to connect to this MySQL server in /var/www/html/index.php on line 19

Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /var/www/html/index.php on line 23

Fatal error: Uncaught Error: Call to a member function fetch_array() on null in /var/www/html/index.php:27 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 27

**Comment by AbhayVAshokan** [comment]
I get the same error. I just cloned the repository and run the following command.
```docker-compose up -d```

![Error-Screenshot](https://user-images.githubusercontent.com/35297280/90543867-e0767580-e1a3-11ea-9d4c-a234febee256.png)

Do I have to do any configurations on my part in my system? I am using ```Ubuntu 20.04```.

**Comment by jcavat** [comment]
Please wait a little while and try again. One of the containers has probably not finished its job. See the log if necessary.

**Comment by AbhayVAshokan** [comment]
> I get the same error. I just cloned the repository and run the following command.
> `docker-compose up -d`
> 
> Do I have to do any configurations on my part in my system? I am using `Ubuntu 20.04`.

I know it's been a while. I figured it out now. `localhost:8001` will be down as long as you have not logged into the `phpmyadmin` dashboard. Just login into the `phpmyadmin` at `localhost:8000` using the credentials provided in `docker-compose.yml` file and everything is up and running as expected.

I guess this issue can be safely closed now.

**Comment by jcavat** [comment]
Thanks for the feedback
