### ISSUE TITLE
database root password 

### ISSUE THREAD

**Issue by ignacioUD** [jcavat/docker-lamp#18]
what is the database password for root

**Comment by magasb1** [comment]
MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: **test**

**Comment by michalkortas** [comment]
Hi. Look at file docker-compose.yml. There are database credentials.

MYSQL_DATABASE: myDb
MYSQL_USER: user
MYSQL_PASSWORD: test
MYSQL_ROOT_PASSWORD: test
