### ISSUE TITLE
No root access to DB :(

### ISSUE THREAD

**Issue by sandipt27** [jcavat/docker-lamp#27]
Following is **mysql part** of **docker-compose.yml** file : 

>     db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: root
            MYSQL_PASSWORD: ''
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
        restart: always
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default

Now, I don't know for what weird reason, but the mysql has added "docker" as user which doesn't have access to create / drop databases.  I suspect, this is because of my earlier trial setup which had user named 'docker' in it and the same is getting carried forwarded for mysql.  The command '**docker-compose up -d**' seems not resetting the mysql image and user "root" is not getting created.

Is there any ways I could add this user "root" ?  Since don't have root access so can't even know if there is any root user added already.   I tried "**docker-compose exec db mysql -u root -p**" with "root" as password, says access denied... with blank password, says access denied...

Any help please ?

Thanks

**Comment by sandipt27** [comment]
btw, forgot to mention, rebuilt the image ample of times... removed images literally, ample of times... removed the containers literally, ample of times... restarted the machine...LITERALLY... still mysql decides to go with "docker" user and no sign of "root" user anywhere....

After ample of trials when got tired, decided to continue with "myDb" database for time being, but needs to create a new database now.  Already did heavy work with setting up server as per my requirements, so would feel really bad if need to remove and all again... :(

**Comment by jcavat** [comment]
did you try `docker-compose down -v` to reset the volume ? It will take into account your new dump file when you restart with `up -d`

**Comment by sandipt27** [comment]
resetting volume would reset the volume for "mysql" only ? OR for complete server setup will be lost including but not limited to apache, php etc ?

**Comment by jcavat** [comment]
only for the volume used by your local container where you run the command. I have no issue with root login/password in my computers, neither on projects based on this snippet. You should use the docker documentation. This is not a problem specific to this snippet.
