### ISSUE TITLE
Question: how can I change the PHP version?

### ISSUE THREAD

**Issue by jschouwstra** [jcavat/docker-lamp#3]
How can I change the PHP version?
For example, I want to update the current image's PHP to 7.2, how would I do that?

**Comment by jcavat** [comment]
You can modify it in the Dockerfile i think :

```
FROM php:7.2-apache 
RUN docker-php-ext-install mysqli
```

**Comment by jcavat** [comment]
You can use these tags:
https://hub.docker.com/_/php/

**Comment by jschouwstra** [comment]
Hey thanks @jcavat
