### ISSUE TITLE
modrevrite

### ISSUE THREAD

**Issue by grekpg** [jcavat/docker-lamp#6]
how enable modrevrite

**Comment by jcavat** [comment]
maybe with `RUN a2enmod rewrite` in the Dockerfile. This is a specifi question related to `php:7.3-apache ` hub. Take a look [https://github.com/docker-library/php](here) and [https://github.com/docker-library/php](here).

**Comment by fran6t** [comment]
@grekpg For .htaccess and rewite i have succes with modify the file Dokerfile like this
FROM php:7.3-apache 
# To active .htaccess valid
RUN ln -s ../mods-available/{expires,headers,rewrite}.load /etc/apache2/mods-enabled/
RUN sed -e '/<Directory \/var\/www\/>/,/<\/Directory>/s/AllowOverride None/AllowOverride All/' -i RUN a2enmod rewrite
RUN docker-php-ext-install mysqli

Thank's jcavat your work permit me first try with docker
