### ISSUE TITLE
Can't change another database

### ISSUE THREAD

**Issue by batisuoc** [jcavat/docker-lamp#9]
I try to change myDB.sql to another *.sql file but when i open phpmyadmin it still show myDb database not my custom database . How can i solve it ?

**Comment by jcavat** [comment]
Try removing the volume. With docker-compose : ´´´docker-compose down -v ´´´

**Comment by jcavat** [comment]
Feedback please !?

**Comment by batisuoc** [comment]
it work !!! thanks for your help.
